# Generated by Django 5.0.4 on 2024-04-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('apptype', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
