# Generated by Django 5.0.4 on 2024-04-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codesnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_intent', models.TextField(blank=True)),
                ('user_input', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('input_type', models.CharField(blank=True, choices=[('question', 'Asking for answers'), ('write code', 'Request to code'), ('explain', 'Asking for Explanation'), ('modify', 'Request to modify code'), ('Add', 'Add a feature or requirement'), ('Remove', 'Remove a feature')], max_length=25)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppwllm.objective')),
            ],
        ),
    ]
