# Generated by Django 5.0.4 on 2024-04-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='apptype',
            field=models.CharField(choices=[('sc', 'script'), ('web', 'webapp'), ('gui', 'graphical'), ('cli', 'commandline')], max_length=3),
        ),
        migrations.AlterField(
            model_name='objective',
            name='experience',
            field=models.CharField(choices=[('nc', 'non-coder'), ('am', 'amatueur'), ('jr', 'junior'), ('md', 'midlevel'), ('sr', 'senior')], max_length=2),
        ),
        migrations.AlterField(
            model_name='objective',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('go', 'Go'), ('rs', 'Rust')], max_length=3),
        ),
    ]
