# Generated by Django 5.0.4 on 2024-04-26 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestore',
            name='msgdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 11, 41, 55, 739048)),
        ),
    ]
