# Generated by Django 5.0.4 on 2024-04-26 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0002_alter_messagestore_msgdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestore',
            old_name='parsedmsg',
            new_name='groqparsed',
        ),
        migrations.AddField(
            model_name='messagestore',
            name='openaiparsed',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='messagestore',
            name='msgdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 25, 58, 154464)),
        ),
    ]
