# Generated by Django 5.0.4 on 2024-04-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0002_alter_objective_apptype_alter_objective_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promptintent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_intent', models.TextField()),
                ('user_question', models.TextField()),
                ('user_feedback', models.TextField()),
                ('user_satisfied', models.BooleanField(default=False)),
                ('llm_question', models.TextField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppwllm.objective')),
            ],
        ),
    ]
