# Generated by Django 5.0.4 on 2024-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0003_promptintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='apptype',
            field=models.CharField(choices=[('sc', 'script'), ('web', 'webapp'), ('gui', 'graphical'), ('cli', 'commandline')], max_length=15),
        ),
        migrations.AlterField(
            model_name='objective',
            name='experience',
            field=models.CharField(choices=[('non-coder', 'non-coder'), ('amatuer', 'amatueur'), ('junior', 'junior'), ('midlevel', 'midlevel'), ('senior', 'senior')], max_length=15),
        ),
        migrations.AlterField(
            model_name='objective',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('go', 'Go'), ('rust', 'Rust')], max_length=15),
        ),
    ]
