# Generated by Django 5.0.4 on 2024-04-26 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0003_rename_parsedmsg_messagestore_groqparsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestore',
            name='msgdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 13, 35, 12, 332686)),
        ),
    ]
