# Generated by Django 5.0.4 on 2024-04-26 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0004_alter_messagestore_msgdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestore',
            name='groqparsed',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='messagestore',
            name='msgdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 15, 1, 43, 737569)),
        ),
        migrations.AlterField(
            model_name='messagestore',
            name='openaiparsed',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='messagestore',
            name='rawcontent',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
