# Generated by Django 5.0.4 on 2024-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0004_alter_objective_apptype_alter_objective_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='challenge',
            field=models.TextField(unique=True),
        ),
    ]
