# Generated by Django 5.0.4 on 2024-04-26 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwllm', '0005_alter_messagestore_groqparsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestore',
            name='msgdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 2, 48, 484501)),
        ),
        migrations.AlterField(
            model_name='rawcontent',
            name='content',
            field=models.TextField(blank=True, default=None, unique=True),
        ),
    ]
